if [[ $(uname -s) = 'Darwin' ]]; then
    # MacOS用設定
    . /usr/local/etc/bash_completion
elif grep -qi microsoft /proc/version 2>/dev/null; then
    # WSLの場合
    alias pbcopy='clip.exe'
elif grep 'NAME="Ubuntu"' /etc/os-release >/dev/null; then
    # Ubuntu用設定
    alias open='xdg-open'
    alias pbcopy='xsel --clipboard --input'
fi

# コマンド補完設定(code-container)
if which code >/dev/null && which docker >/dev/null; then
    _code_container() { COMPREPLY=( $(compgen -W "$(docker ps -a --format '{{.Names}}')" -- ${COMP_WORDS[COMP_CWORD]}) ); }
    complete -F _code_container code-container
fi
